version: '3'
services:
  mysql:
    image: mysql:5.7
   # stdin_open: true
    #stdin_open: true # docker run -i
    #tty: true # docker run -t
    #restart: "no"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tSeriesDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    working_dir: /app
    volumes:
      - .:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

