version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tSeriesDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    working_dir: /app
    volumes:
      - .:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"

networks:
  default:
    external:
      name: red_local
